/**
 * One-click content presets for shorts/reels — applies typography, layout,
 * and animation to every caption block.
 */
export const LOOK_PRESETS = [
  {
    id: 'documentary',
    name: 'Documentary',
    emoji: '🎬',
    tagline: 'Calm centered subs',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: '34px',
    fontWeight: '600',
    fontStyle: 'normal',
    color: '#ffffff',
    textTransform: 'none',
    textAlign: 'center',
    strokeColor: '#000000',
    strokeWidth: 0.1,
    shadow: true,
    underline: false,
    strike: false,
    xRel: 0.5,
    yRel: 0.88,
    animation: 'fade',
    animationDuration: 0.58,
    animationAnimateAll: true
  },
  {
    id: 'movie-shorts',
    name: 'Movie Shorts',
    emoji: '🍿',
    tagline: 'Cinematic punch-ins',
    fontFamily: '"Bebas Neue", Impact, sans-serif',
    fontSize: '54px',
    fontWeight: '900',
    fontStyle: 'normal',
    color: '#ffffff',
    textTransform: 'uppercase',
    textAlign: 'center',
    strokeColor: '#000000',
    strokeWidth: 0.14,
    shadow: true,
    underline: false,
    strike: false,
    xRel: 0.5,
    yRel: 0.76,
    animation: 'scale-in',
    animationDuration: 0.42,
    animationAnimateAll: false
  },
  {
    id: 'news',
    name: 'News',
    emoji: '📰',
    tagline: 'Breaking headline punch',
    fontFamily: 'Oswald, Impact, sans-serif',
    fontSize: '44px',
    fontWeight: '700',
    fontStyle: 'normal',
    color: '#ffffff',
    textTransform: 'uppercase',
    textAlign: 'center',
    strokeColor: '#000000',
    strokeWidth: 0.14,
    shadow: true,
    underline: false,
    strike: false,
    xRel: 0.5,
    yRel: 0.8,
    animation: 'fly-in-left',
    animationDuration: 0.32,
    animationAnimateAll: false
  },
  {
    id: 'viral-reels',
    name: 'Viral Reels',
    emoji: '🔥',
    tagline: 'TikTok / IG word-pop',
    fontFamily: 'Anton, Impact, sans-serif',
    fontSize: '58px',
    fontWeight: '900',
    fontStyle: 'normal',
    color: '#fbbf24',
    textTransform: 'uppercase',
    textAlign: 'center',
    strokeColor: '#000000',
    strokeWidth: 0.18,
    shadow: true,
    underline: false,
    strike: false,
    xRel: 0.5,
    yRel: 0.78,
    animation: 'pop',
    animationDuration: 0.22,
    animationAnimateAll: false
  },
  {
    id: 'vlog',
    name: 'Vlog',
    emoji: '📸',
    tagline: 'Clean creator captions',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: '38px',
    fontWeight: '700',
    fontStyle: 'normal',
    color: '#ffffff',
    textTransform: 'none',
    textAlign: 'center',
    strokeColor: '#000000',
    strokeWidth: 0.09,
    shadow: true,
    underline: false,
    strike: false,
    xRel: 0.5,
    yRel: 0.86,
    animation: 'fade',
    animationDuration: 0.5,
    animationAnimateAll: true
  },
  {
    id: 'podcast',
    name: 'Podcast Clips',
    emoji: '🎙️',
    tagline: 'Talking-head highlights',
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: '42px',
    fontWeight: '800',
    fontStyle: 'normal',
    color: '#f4f4f5',
    textTransform: 'none',
    textAlign: 'center',
    strokeColor: '#18181b',
    strokeWidth: 0.08,
    shadow: true,
    underline: false,
    strike: false,
    xRel: 0.5,
    yRel: 0.84,
    animation: 'slide-up',
    animationDuration: 0.4,
    animationAnimateAll: false
  },
  {
    id: 'educational',
    name: 'Educational',
    emoji: '📚',
    tagline: 'Explainers & tutorials',
    fontFamily: '"Open Sans", Inter, sans-serif',
    fontSize: '36px',
    fontWeight: '700',
    fontStyle: 'normal',
    color: '#e0e7ff',
    textTransform: 'none',
    textAlign: 'center',
    strokeColor: '#1e1b4b',
    strokeWidth: 0.07,
    shadow: false,
    underline: false,
    strike: false,
    xRel: 0.5,
    yRel: 0.82,
    animation: 'typewriter',
    animationDuration: 0.55,
    animationAnimateAll: false
  },
  {
    id: 'gaming',
    name: 'Gaming',
    emoji: '🎮',
    tagline: 'High-energy hype edits',
    fontFamily: 'Oswald, Impact, sans-serif',
    fontSize: '50px',
    fontWeight: '900',
    fontStyle: 'normal',
    color: '#22d3ee',
    textTransform: 'uppercase',
    textAlign: 'center',
    strokeColor: '#0c0a1a',
    strokeWidth: 0.12,
    shadow: true,
    underline: false,
    strike: false,
    xRel: 0.5,
    yRel: 0.72,
    animation: 'bounce',
    animationDuration: 0.28,
    animationAnimateAll: false
  }
];
