export const KEYBOARD_SHORTCUTS = [
  { keys: ['Space'], label: 'Play / Pause video' },
  { keys: ['Ctrl', 'Z'], label: 'Undo last edit' },
  { keys: ['Ctrl', 'Shift', 'Z'], label: 'Redo' },
  { keys: ['Ctrl', 'Y'], label: 'Redo (alternate)' },
  { keys: ['Delete'], label: 'Delete selected caption or element' },
  { keys: ['C'], label: 'Cut / split selected clip at playhead' },
  { keys: ['←', '→'], label: 'Seek backward / forward (0.1s)' },
  { keys: ['Ctrl', '+'], label: 'Zoom in preview' },
  { keys: ['Ctrl', '-'], label: 'Zoom out preview' },
  { keys: ['Ctrl', '0'], label: 'Reset preview zoom & pan' },
  { keys: ['N'], label: 'Add new caption block' },
  { keys: ['1'], label: 'Open Preset Caption panel' },
  { keys: ['2'], label: 'Open Preset Font panel' },
  { keys: ['3'], label: 'Open Custom Font panel' },
  { keys: ['4'], label: 'Open Elements panel' },
  { keys: ['5'], label: 'Open Custom Animate panel' },
  { keys: ['Esc'], label: 'Back to editor tools menu' },
  { keys: ['?'], label: 'Show keyboard shortcuts' }
];
